[package]
name = "authenticator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
tokio-postgres = "0.7.7"
rust-argon2 = "1.0.0"
sha2 = "0.10.6"
reqwest = { version = "0.11.15", features = ["json"] }
clap = { version = "4.1.11", features = ["derive"] }
tokio = { version = "1.26.0", features = ["full"] }
serde = { version = "1.0.158", features = ["derive"] }
serde_json = "1.0.94"
auth-service-api = {version = "*", git = "https://github.com/innexgo/auth-service-api" }
mail-service-api = {version = "*", git = "https://github.com/innexgo/mail-service-api", features=["client"]}
base64-url = "2.0.0"
actix-web = "4.3.1"
env_logger = "0.10.0"
log = "0.4.17"
actix-cors = "0.6.4"
